sonar.projectKey=Job-Scheduler-2
sonar.projectName=Job-Scheduler-2
sonar.projectVersion=0.1.0

sonar.sources=backend
sonar.tests=tests
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8

sonar.exclusions=migrations/**,deploy/**,docs/**,tmp/**,coverage/**,**/__pycache__/**
sonar.test.inclusions=tests/**/*.py
sonar.python.coverage.reportPaths=coverage/coverage.xml
sonar.python.xunit.reportPath=coverage/junit.xml
sonar.python.xunit.skipDetails=true
