apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: job-scheduler
resources:
  - 00-namespace.yaml
  - 01-config.yaml
  - 02-postgres.yaml
  - 03-redis.yaml
  - 04-migrate-job.yaml
  - 05-api.yaml
  - 06-scheduler.yaml
  - 07-worker.yaml
  - 08-ingress.yaml
